/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_nondev_nonlua_Lua */

#ifndef _Included_io_nondev_nonlua_Lua
#define _Included_io_nondev_nonlua_Lua
#ifdef __cplusplus
extern "C" {
#endif
#undef io_nondev_nonlua_Lua_GLOBALS
#define io_nondev_nonlua_Lua_GLOBALS -10002L
#undef io_nondev_nonlua_Lua_REGISTRY
#define io_nondev_nonlua_Lua_REGISTRY -10000L
#undef io_nondev_nonlua_Lua_NONE
#define io_nondev_nonlua_Lua_NONE -1L
#undef io_nondev_nonlua_Lua_NIL
#define io_nondev_nonlua_Lua_NIL 0L
#undef io_nondev_nonlua_Lua_BOOLEAN
#define io_nondev_nonlua_Lua_BOOLEAN 1L
#undef io_nondev_nonlua_Lua_LIGHTUSERDATA
#define io_nondev_nonlua_Lua_LIGHTUSERDATA 2L
#undef io_nondev_nonlua_Lua_NUMBER
#define io_nondev_nonlua_Lua_NUMBER 3L
#undef io_nondev_nonlua_Lua_STRING
#define io_nondev_nonlua_Lua_STRING 4L
#undef io_nondev_nonlua_Lua_TABLE
#define io_nondev_nonlua_Lua_TABLE 5L
#undef io_nondev_nonlua_Lua_FUNCTION
#define io_nondev_nonlua_Lua_FUNCTION 6L
#undef io_nondev_nonlua_Lua_USERDATA
#define io_nondev_nonlua_Lua_USERDATA 7L
#undef io_nondev_nonlua_Lua_THREAD
#define io_nondev_nonlua_Lua_THREAD 8L
#undef io_nondev_nonlua_Lua_MULTRET
#define io_nondev_nonlua_Lua_MULTRET -1L
#undef io_nondev_nonlua_Lua_YIELD
#define io_nondev_nonlua_Lua_YIELD 1L
#undef io_nondev_nonlua_Lua_ERR_RUNTIME
#define io_nondev_nonlua_Lua_ERR_RUNTIME 2L
#undef io_nondev_nonlua_Lua_ERR_SYNTAX
#define io_nondev_nonlua_Lua_ERR_SYNTAX 3L
#undef io_nondev_nonlua_Lua_ERR_MEMORY
#define io_nondev_nonlua_Lua_ERR_MEMORY 4L
#undef io_nondev_nonlua_Lua_ERR_HANDLER
#define io_nondev_nonlua_Lua_ERR_HANDLER 5L
#undef io_nondev_nonlua_Lua_OP_EQUAL
#define io_nondev_nonlua_Lua_OP_EQUAL 1L
#undef io_nondev_nonlua_Lua_OP_LOWER
#define io_nondev_nonlua_Lua_OP_LOWER 2L
#undef io_nondev_nonlua_Lua_OP_LOWEREQUAL
#define io_nondev_nonlua_Lua_OP_LOWEREQUAL 3L
/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpen
 * Signature: (I)Lio/nondev/nonlua/CPtr;
 */
JNIEXPORT jobject JNICALL Java_io_nondev_nonlua_Lua_jniOpen
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniClose
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniClose
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenBase
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenBase
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenCoroutine
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenCoroutine
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenDebug
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenDebug
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenIo
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenIo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenJava
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenJava
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenMath
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenMath
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenOs
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenOs
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenPackage
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenPackage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenSocket
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenSocket
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenString
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenTable
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenTable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniOpenUtf8
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniOpenUtf8
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniLoadBuffer
 * Signature: (Lio/nondev/nonlua/CPtr;[BJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniLoadBuffer
  (JNIEnv *, jclass, jobject, jbyteArray, jlong, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniLoadString
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniLoadString
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniRunBuffer
 * Signature: (Lio/nondev/nonlua/CPtr;[BJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniRunBuffer
  (JNIEnv *, jclass, jobject, jbyteArray, jlong, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniRunString
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniRunString
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniNewThread
 * Signature: (Lio/nondev/nonlua/CPtr;)Lio/nondev/nonlua/CPtr;
 */
JNIEXPORT jobject JNICALL Java_io_nondev_nonlua_Lua_jniNewThread
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushNil
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushNil
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushNumber
 * Signature: (Lio/nondev/nonlua/CPtr;D)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushNumber
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushString
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushString
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushBoolean
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushBoolean
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushFunction
 * Signature: (Lio/nondev/nonlua/CPtr;Lio/nondev/nonlua/LuaFunction;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushFunction
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushObject
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushObject
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushArray
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushArray
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsNumber
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsNumber
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsBoolean
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsBoolean
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsString
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsString
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsFunction
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsFunction
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsObject
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsObject
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsTable
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsTable
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsUserdata
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsUserdata
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsNil
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsNil
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniIsNone
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniIsNone
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniToNumber
 * Signature: (Lio/nondev/nonlua/CPtr;I)D
 */
JNIEXPORT jdouble JNICALL Java_io_nondev_nonlua_Lua_jniToNumber
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniToBoolean
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniToBoolean
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniToString
 * Signature: (Lio/nondev/nonlua/CPtr;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_nondev_nonlua_Lua_jniToString
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniToObject
 * Signature: (Lio/nondev/nonlua/CPtr;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_nondev_nonlua_Lua_jniToObject
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetGlobal
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniGetGlobal
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSetGlobal
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniSetGlobal
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGet
 * Signature: (Lio/nondev/nonlua/CPtr;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniGet
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSet
 * Signature: (Lio/nondev/nonlua/CPtr;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniSet
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetI
 * Signature: (Lio/nondev/nonlua/CPtr;II)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniGetI
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSetI
 * Signature: (Lio/nondev/nonlua/CPtr;II)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniSetI
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetTop
 * Signature: (Lio/nondev/nonlua/CPtr;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniGetTop
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSetTop
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniSetTop
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPop
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPop
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPushValue
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniPushValue
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniCopy
 * Signature: (Lio/nondev/nonlua/CPtr;II)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniCopy
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniRemove
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniRemove
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniInsert
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniInsert
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniReplace
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniReplace
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniConcat
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniConcat
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniLen
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniLen
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniCompare
 * Signature: (Lio/nondev/nonlua/CPtr;III)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniCompare
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniType
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniType
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniTypeName
 * Signature: (Lio/nondev/nonlua/CPtr;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_nondev_nonlua_Lua_jniTypeName
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniRef
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniRef
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniUnRef
 * Signature: (Lio/nondev/nonlua/CPtr;II)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniUnRef
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniCall
 * Signature: (Lio/nondev/nonlua/CPtr;II)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniCall
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniPcall
 * Signature: (Lio/nondev/nonlua/CPtr;III)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniPcall
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniNewTable
 * Signature: (Lio/nondev/nonlua/CPtr;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniNewTable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetTable
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniGetTable
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSetTable
 * Signature: (Lio/nondev/nonlua/CPtr;I)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniSetTable
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniNewMetatable
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniNewMetatable
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetMetatable
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniGetMetatable
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetMetatableStr
 * Signature: (Lio/nondev/nonlua/CPtr;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_nondev_nonlua_Lua_jniGetMetatableStr
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniSetMetatable
 * Signature: (Lio/nondev/nonlua/CPtr;I)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniSetMetatable
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniCallmeta
 * Signature: (Lio/nondev/nonlua/CPtr;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniCallmeta
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     io_nondev_nonlua_Lua
 * Method:    jniGetmeta
 * Signature: (Lio/nondev/nonlua/CPtr;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_nondev_nonlua_Lua_jniGetmeta
  (JNIEnv *, jclass, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
